server:
  port: 81
  servlet:
    context-path: /threec-generator
#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
renren:
  database: mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-read.mysql.svc.cluster.local:3306/goarchery-test?useSSL=false&serverTimezone=UTC
    username: root
    password: MSStarForever*00
  #oracle配置
  #    driverClassName: oracle.jdbc.OracleDriver
  #    url: jdbc:oracle:thin:@127.0.0.1:1521:xe
  #    username: root
  #    password: 123456
  #SQLServer配置
  #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=fast
  #    username: root
  #    password: 123456
  #PostgreSQL配置
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://127.0.0.1:5432/fast
  #    username: root
  #    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql